### PR TITLE
Bash tutorial

### PR DESCRIPTION
**Pull request by fadinammour**
Request to make a branch

### CODE REVIEW

**Comment by sfarrens** [comment]
Hi @fadinammour This PR is pointing to `CosmoStat:master`, when I assume you intended to point to something like `CosmoStat:bash_tutorial`.

**Comment by fadinammour** [comment]
You're right but I didn't manage to create `CosmoStat:bash_tutorial`. I thought that it was possible for the admin to redirect the branch

**Comment by sfarrens** [comment]
OK, I have created and new branch called `bash_tutorial` and pointed your PR to this branch. I had to resolve some conflicts with the readme. Please check that everything is OK and that you want to include all 38 files. Please also delete the `.DS_Store` file.

Once that is done and you are happy I can merge it.

**Review by fadinammour — COMMENTED** [review]
Isn't it better to replace `fadinammour` with `CosmoStat` in the link to mybinder?

**Pull request merged**
